### ISSUE TITLE
Get runStockAssessment running

### ISSUE THREAD

**Issue by smartell** [smartell/iSCAM#19]
I'm going to let you pull the trigger on the big one and get it running. You've worked hard on this, so it would be good to see you make the final function work.

After you get the WriteDataFile bug fixed,

Try and get th runStockAssessment model running. one line of code should do it:

system("./iscam -mseRUN.dat");  

and make sure mssRUN.dat has the simulated datafile name in it.

Then Skype me with huge amounts of excitement!!!!!

:)  See you Thursday.

**Comment by catarinawor** [comment]
I guess this one is closed too . =)
