### ISSUE TITLE
Bug in calcAgeComps with prospective adjustment

### ISSUE THREAD

**Issue by catarinawor** [smartell/iSCAM#29]
Approx Line 2953
Bug in redimensioning O (obs age comps) and P (predicted age comps). 
iaa+ is the total number of lines that should be discarded.

**Comment by smartell** [comment]
Fixed issue 29. Added counters in data section based on number of retrospective years and prospective years and then looped over all observations and only extract comp vector if iyr >=syr or <=nyr.
